package baselineguard

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/hairglasses-studio/codexkit/mcpsync"
)

func setupCompliantRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()

	writeFile(t, dir, "AGENTS.md", "# Test\n\n> Canonical instructions: AGENTS.md\n")
	writeFile(t, dir, "CLAUDE.md", "# Test\n\nThis repo uses [AGENTS.md](AGENTS.md) as the canonical instruction file.\n")
	writeFile(t, dir, "GEMINI.md", "# Test\n\nThis repo uses [AGENTS.md](AGENTS.md) as the canonical instruction file.\n")
	writeFile(t, dir, ".claude/settings.json", "{}\n")
	writeFile(t, dir, ".gemini/settings.json", "{\n  \"context\": {\n    \"fileName\": [\"AGENTS.md\", \"GEMINI.md\"]\n  }\n}\n")
	writeFile(t, dir, ".github/copilot-instructions.md", "See AGENTS.md in the repository root.\n")
	writeFile(t, dir, ".codex/config.toml", `
approval_policy = "on-request"

[profiles.readonly_quiet]
approval_policy = "never"

[profiles.review]
approval_policy = "on-request"

[profiles.workspace_auto]
approval_policy = "on-failure"

[profiles.ci_json]
approval_policy = "never"
`)
	writeFile(t, dir, ".codex/agents/reviewer.toml", `name = "reviewer"`)
	writeFile(t, dir, ".codex/agents/repo_explorer.toml", `name = "repo_explorer"`)

	surface, _ := json.Marshal(map[string]any{
		"version": 1,
		"skills":  []map[string]any{{"name": "test_skill"}},
	})
	writeFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeFile(t, dir, ".agents/skills/test_skill/SKILL.md", "---\nname: test_skill\ndescription: \"Core build, test, release, and maintenance workflow for the test repo.\"\nallowed-tools:\n  - Bash\n---\n# Test\n")
	writeFile(t, dir, ".claude/skills/test_skill/SKILL.md", "---\nname: test_skill\ndescription: 'Core build, test, release, and maintenance workflow for the test repo.'\nallowed-tools:\n  - Bash\n---\n\n<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->\n\nCompatibility mirror of the canonical `test_skill` skill.\n\n\n# Test\n")
	writeFile(t, dir, ".claude/skills/test-skill/SKILL.md", "---\nname: test-skill\ndescription: 'Hyphenated compatibility alias for the test_skill workflow.'\nallowed-tools:\n  - Bash\n---\n\n<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->\n\nCompatibility alias for the canonical `test_skill` skill.\n\n\n# Test\n")

	return dir
}

func writeFile(t *testing.T, base, name, content string) {
	t.Helper()
	path := filepath.Join(base, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func TestCheck_CompliantRepo(t *testing.T) {
	dir := setupCompliantRepo(t)
	report := Check(dir)

	if !report.Passed {
		for _, f := range report.Findings {
			if !f.Passed {
				t.Errorf("unexpected failure: %s — %s", f.Check, f.Message)
			}
		}
		t.Fatalf("expected PASS, got %d failures", report.Failed)
	}
}

func TestCheck_MissingAgentsMd(t *testing.T) {
	dir := setupCompliantRepo(t)
	os.Remove(filepath.Join(dir, "AGENTS.md"))

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL for missing AGENTS.md")
	}
	found := false
	for _, f := range report.Findings {
		if f.Check == "required_file" && !f.Passed && f.Message == "missing: AGENTS.md" {
			found = true
		}
	}
	if !found {
		t.Error("expected finding for missing AGENTS.md")
	}
}

func TestCheck_MissingCanonicalPattern(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, "AGENTS.md", "# Test\n\nNo canonical line here.\n")

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL for missing canonical pattern")
	}
}

func TestCheck_MissingProfile(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".codex/config.toml", `
[profiles.readonly_quiet]
[profiles.review]
`)

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL for missing profiles")
	}
	failCount := 0
	for _, f := range report.Findings {
		if f.Check == "profile" && !f.Passed {
			failCount++
		}
	}
	if failCount != 2 {
		t.Fatalf("expected 2 missing profiles, got %d", failCount)
	}
}

func TestCheck_InvalidCodexConfigTOML(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".codex/config.toml", `
approval_policy = "on-request"
env_key_instructions = "source "$HOME/bad" && broken"
`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "codex_config_toml" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Fatal("expected codex_config_toml failure for invalid TOML")
	}
}

func TestCheck_MissingGeminiContextBridge(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".gemini/settings.json", "{}\n")

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "gemini_context_bridge" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected gemini_context_bridge failure when AGENTS.md is not in context.fileName")
	}
}

func TestCheck_IgnoresExampleOnlyMCPServers(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", "{\n  \"mcpServers\": {\n    \"_example_stdio_server\": {\n      \"command\": \"go\"\n    }\n  }\n}\n")

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "gemini_mcp_bridge" && !f.Passed {
			t.Fatalf("did not expect gemini_mcp_bridge failure for example-only MCP config: %s", f.Message)
		}
	}
}

func TestCheck_MCPPortabilityFlagsRelativeCWD(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", `{
  "mcpServers": {
    "demo": {
      "command": "bash",
      "args": ["./scripts/run-demo.sh"],
      "cwd": "."
    }
  }
}
`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "mcp_portability" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected mcp_portability failure for repo-relative MCP launch")
	}
}

func TestCheck_MCPPortabilityFlagsGeneratedConfigCWD(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", `{
  "mcpServers": {
    "demo": {
      "command": "bash",
      "args": ["-c", "exec bash \"$HOME/demo.sh\""]
    }
  }
}
`)
	writeFile(t, dir, ".codex/config.toml", `
[profiles.readonly_quiet]
[profiles.review]
[profiles.workspace_auto]
[profiles.ci_json]

[mcp_servers.demo]
cwd = "."
`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "mcp_portability" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected mcp_portability failure for generated config cwd")
	}
}

func TestCheck_DashCaseAgent(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".codex/agents/my-agent.toml", `name = "my-agent"`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "agent_naming" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected agent_naming failure for dash-case filename")
	}
}

func TestCheck_InvalidSurfaceJSON(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/skills/surface.yaml", "not json at all")

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "skill_surface" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected skill_surface failure for invalid JSON")
	}
}

func TestCheck_MissingSkillFile(t *testing.T) {
	dir := setupCompliantRepo(t)
	os.RemoveAll(filepath.Join(dir, ".agents/skills/test_skill"))

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "skill_file" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected skill_file failure for missing SKILL.md")
	}
}

func TestCheck_NoSurface(t *testing.T) {
	dir := setupCompliantRepo(t)
	os.Remove(filepath.Join(dir, ".agents/skills/surface.yaml"))

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "skill_surface" && !f.Passed {
			t.Error("missing surface.yaml should not cause failure")
		}
	}
}

func TestCheck_SkillSyncAllowsGeneratedClaudeMirror(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/skills/surface.yaml", `{"version":1,"skills":[{"name":"test_skill","claude_include_canonical":true}]}`)
	writeFile(t, dir, ".agents/skills/test_skill/SKILL.md", `---
name: test_skill
description: "Core build, test, release, and maintenance workflow for the test repo."
allowed-tools:
  - Bash
---

# Test Skill

Use this skill for the default repo workflow.
`)
	writeFile(t, dir, ".claude/skills/test_skill/SKILL.md", `---
name: test_skill
description: 'Core build, test, release, and maintenance workflow for the test repo.'
allowed-tools:
  - Bash
---

<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->

Compatibility mirror of the canonical `+"`test_skill`"+` skill.


# Test Skill

Use this skill for the default repo workflow.
`)
	writeFile(t, dir, ".claude/skills/test-skill/SKILL.md", `---
name: test-skill
description: 'Hyphenated compatibility alias for the test_skill workflow.'
allowed-tools:
  - Bash
---

<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->

Compatibility alias for the canonical `+"`test_skill`"+` skill.


# Test Skill

Use this skill for the default repo workflow.
`)

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "skill_sync" && !f.Passed {
			t.Fatalf("expected generated Claude mirror to pass, got: %s", f.Message)
		}
	}
}

func TestCheck_MCPSyncHonorsProfilePolicy(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", `{
  "mcpServers": {
    "demo": {
      "command": "bash",
      "args": ["-lc", "exec ./scripts/run-demo.sh"]
    }
  }
}
`)
	writeFile(t, dir, ".codex/mcp-profile-policy.json", `{
  "version": 1,
  "profiles": [
    {
      "name": "demo_review",
      "from": "demo",
      "comment": "Read-only demo profile."
    }
  ]
}
`)
	writeFile(t, dir, ".codex/config.toml", `
[profiles.readonly_quiet]
approval_policy = "never"

[profiles.review]
approval_policy = "on-request"

[profiles.workspace_auto]
approval_policy = "on-failure"

[profiles.ci_json]
approval_policy = "never"
`)
	if report := mcpsync.Sync(dir, false); len(report.Errors) > 0 {
		t.Fatalf("unexpected mcpsync errors: %v", report.Errors)
	}

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "mcp_sync" && !f.Passed {
			t.Fatalf("expected policy-derived MCP server to pass, got: %s", f.Message)
		}
	}
}
