package baselineguard

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/hairglasses-studio/codexkit/mcpsync"
)

func setupCompliantRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()

	writeFile(t, dir, "AGENTS.md", "# Test\n\n> Canonical instructions: AGENTS.md\n")
	writeFile(t, dir, "CLAUDE.md", "# Test\n\nThis repo uses [AGENTS.md](AGENTS.md) as the canonical instruction file.\n")
	writeFile(t, dir, ".claude/settings.json", "{}\n")
	writeFile(t, dir, ".agents/hooks.json", "{}\n")
	writeFile(t, dir, ".agents/agents/reviewer/agent.md", "---\nname: reviewer\ndescription: Review changes.\n---\n")
	writeFile(t, dir, ".codex/config.toml", `
approval_policy = "on-request"
`)
	writeFile(t, dir, ".codex/agents/reviewer.toml", `name = "reviewer"`)
	writeFile(t, dir, ".codex/agents/repo_explorer.toml", `name = "repo_explorer"`)

	surface, _ := json.Marshal(map[string]any{
		"version": 1,
		"skills":  []map[string]any{{"name": "test_skill"}},
	})
	writeFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeFile(t, dir, ".agents/skills/test_skill/SKILL.md", "---\nname: test_skill\ndescription: \"Core build, test, release, and maintenance workflow for the test repo.\"\nallowed-tools:\n  - Bash\n---\n# Test\n")
	writeFile(t, dir, ".claude/skills/test_skill/SKILL.md", "---\nname: test_skill\ndescription: 'Core build, test, release, and maintenance workflow for the test repo.'\nallowed-tools:\n  - Bash\n---\n\n<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->\n\nCompatibility mirror of the canonical `test_skill` skill.\n\n\n# Test\n")
	writeFile(t, dir, ".claude/skills/test-skill/SKILL.md", "---\nname: test-skill\ndescription: 'Hyphenated compatibility alias for the test_skill workflow.'\nallowed-tools:\n  - Bash\n---\n\n<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->\n\nCompatibility alias for the canonical `test_skill` skill.\n\n\n# Test\n")

	return dir
}

func writeFile(t *testing.T, base, name, content string) {
	t.Helper()
	path := filepath.Join(base, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func TestCheck_CompliantRepo(t *testing.T) {
	dir := setupCompliantRepo(t)
	report := Check(dir)

	if !report.Passed {
		for _, f := range report.Findings {
			if !f.Passed {
				t.Errorf("unexpected failure: %s — %s", f.Check, f.Message)
			}
		}
		t.Fatalf("expected PASS, got %d failures", report.Failed)
	}
}

func TestDiscoverWorkspaceTargetsUsesManifestAndSkipsNonGitRepos(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "workspace/manifest.json", `{
  "version": 2,
  "repos": [
    {"name": "active", "category": "application", "scope": "active_first_party", "language": "Go", "baseline_target": true, "go_work_member": false, "lifecycle": "canonical"},
    {"name": "operator", "category": "hub", "scope": "active_operator", "language": "Shell", "baseline_target": false, "go_work_member": false, "lifecycle": "canonical"},
    {"name": "compat", "category": "supporting", "scope": "compatibility_only", "language": "Go", "baseline_target": false, "go_work_member": false, "lifecycle": "compatibility"},
    {"name": "missing", "category": "application", "scope": "active_first_party", "language": "Go", "baseline_target": true, "go_work_member": false, "lifecycle": "canonical"}
  ]
}
`)
	if err := os.MkdirAll(filepath.Join(root, "active", ".git"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "operator", ".git"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "compat", ".git"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "missing"), 0755); err != nil {
		t.Fatal(err)
	}

	targets, err := DiscoverWorkspaceTargets(root)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{filepath.Join(root, "active"), filepath.Join(root, "operator")}
	if !equalStrings(targets, want) {
		t.Fatalf("targets = %#v, want %#v", targets, want)
	}
}

func TestCheck_MissingAgentsMd(t *testing.T) {
	dir := setupCompliantRepo(t)
	os.Remove(filepath.Join(dir, "AGENTS.md"))

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL for missing AGENTS.md")
	}
	found := false
	for _, f := range report.Findings {
		if f.Check == "required_file" && !f.Passed && f.Message == "missing: AGENTS.md" {
			found = true
		}
	}
	if !found {
		t.Error("expected finding for missing AGENTS.md")
	}
}

func TestCheck_RetiredProviderMirrorsAbsentPasses(t *testing.T) {
	dir := setupCompliantRepo(t)

	report := Check(dir)
	found := 0
	for _, f := range report.Findings {
		if f.Check == "retired_provider_mirror" {
			found++
			if !f.Passed {
				t.Errorf("expected retired_provider_mirror to pass when absent, got failure: %s", f.Message)
			}
		}
	}
	if found != len(RetiredProviderMirrors) {
		t.Fatalf("expected %d retired_provider_mirror findings, got %d", len(RetiredProviderMirrors), found)
	}
}

func TestCheck_RetiredProviderMirrorPresentFails(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, "GEMINI.md", "# retired\n")

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL when a retired provider mirror is present")
	}
	found := false
	for _, f := range report.Findings {
		if f.Check == "retired_provider_mirror" && !f.Passed && f.Message == "retired provider mirror present — remove it: GEMINI.md" {
			found = true
		}
	}
	if !found {
		t.Error("expected finding for present GEMINI.md")
	}
}

func TestCheck_RetiredProviderMirrorCoversAllRetiredPaths(t *testing.T) {
	for _, name := range RetiredProviderMirrors {
		name := name
		t.Run(name, func(t *testing.T) {
			dir := setupCompliantRepo(t)
			writeFile(t, dir, name, "retired\n")

			report := Check(dir)
			found := false
			for _, f := range report.Findings {
				if f.Check == "retired_provider_mirror" && !f.Passed && strings.Contains(f.Message, name) {
					found = true
				}
			}
			if !found {
				t.Errorf("expected retired_provider_mirror failure for %s", name)
			}
		})
	}
}

func TestCheck_AddsStructuredRemediation(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".claude/skills/test_skill/SKILL.md", "# stale\n")

	report := Check(dir)
	var skillSync *Finding
	for i := range report.Findings {
		if report.Findings[i].Check == "skill_sync" && !report.Findings[i].Passed {
			skillSync = &report.Findings[i]
			break
		}
	}
	if skillSync == nil {
		t.Fatal("expected failed skill_sync finding")
	}
	if len(skillSync.Remediation) != 1 {
		t.Fatalf("expected one remediation, got %#v", skillSync.Remediation)
	}
	remediation := skillSync.Remediation[0]
	if remediation.Kind != "generator" {
		t.Fatalf("remediation kind = %q, want generator", remediation.Kind)
	}
	wantCommand := []string{"codexkit", "skills", "sync", dir, "--quiet-warnings"}
	if !equalStrings(remediation.Command, wantCommand) {
		t.Fatalf("remediation command = %#v, want %#v", remediation.Command, wantCommand)
	}
}

func TestCheck_MissingCanonicalPattern(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, "AGENTS.md", "# Test\n\nNo canonical line here.\n")

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL for missing canonical pattern")
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func TestCheck_RejectsProjectLocalProfiles(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".codex/config.toml", `
[profiles.readonly_quiet]
[profiles.review]
`)

	report := Check(dir)
	if report.Passed {
		t.Fatal("expected FAIL for unsupported project-local profiles")
	}
	found := false
	for _, f := range report.Findings {
		if f.Check == "project_local_profiles" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Fatal("expected project_local_profiles failure")
	}
}

func TestCheck_InvalidCodexConfigTOML(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".codex/config.toml", `
approval_policy = "on-request"
env_key_instructions = "source "$HOME/bad" && broken"
`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "codex_config_toml" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Fatal("expected codex_config_toml failure for invalid TOML")
	}
}

func TestCheck_InvalidAGYHooks(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/hooks.json", "{broken\n")

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "agy_hooks_json" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected agy_hooks_json failure for malformed native AGY hooks")
	}
}

func TestCheck_RejectsFlatAGYAgentFiles(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/agents/flat.md", "# not native AGY layout\n")

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "agy_agent_layout" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected agy_agent_layout failure for flat .agents/agents file")
	}
}

func TestCheck_SyncWrapperPortabilityFlagsCallerCWDAndGoWorkDependence(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, "scripts/hg-skill-surface-sync.sh", "#!/usr/bin/env bash\nset -euo pipefail\nrepo_root=\"$(git rev-parse --show-toplevel)\"\ncd \"$repo_root\"\ngo run ./cmd/demo-sync --skills\n")
	writeFile(t, dir, "scripts/codex-mcp-sync.sh", "#!/usr/bin/env bash\nset -euo pipefail\nrepo_root=\"$(git rev-parse --show-toplevel)\"\ncd \"$repo_root\"\ngo run ./cmd/demo-sync --codex\n")

	report := Check(dir)
	failCount := 0
	for _, f := range report.Findings {
		if f.Check == "sync_wrapper_portability" && !f.Passed {
			failCount++
		}
	}
	if failCount != 2 {
		t.Fatalf("expected 2 sync_wrapper_portability failures, got %d", failCount)
	}
}

func TestCheck_SyncWrapperPortabilityAcceptsPortableWrappers(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, "scripts/hg-skill-surface-sync.sh", "#!/usr/bin/env bash\nset -euo pipefail\nscript_dir=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\nrepo_root=\"$(cd \"$script_dir/..\" && pwd)\"\ncd \"$repo_root\"\nGOWORK=off go run ./cmd/demo-sync --skills\n")
	writeFile(t, dir, "scripts/codex-mcp-sync.sh", "#!/usr/bin/env bash\nset -euo pipefail\nscript_dir=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\nrepo_root=\"$(cd \"$script_dir/..\" && pwd)\"\ncd \"$repo_root\"\nGOWORK=off go run ./cmd/demo-sync --codex\n")

	report := Check(dir)
	passCount := 0
	for _, f := range report.Findings {
		if f.Check == "sync_wrapper_portability" && f.Passed {
			passCount++
		}
	}
	if passCount != 2 {
		t.Fatalf("expected 2 passing sync_wrapper_portability findings, got %d", passCount)
	}
}

func TestCheck_IgnoresExampleOnlyMCPServers(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", "{\n  \"mcpServers\": {\n    \"_example_stdio_server\": {\n      \"command\": \"go\"\n    }\n  }\n}\n")

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "mcp_portability" && !f.Passed {
			t.Fatalf("did not expect mcp_portability failure for example-only MCP config: %s", f.Message)
		}
	}
}

func TestCheck_MCPPortabilityFlagsRelativeCWD(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", `{
  "mcpServers": {
    "demo": {
      "command": "bash",
      "args": ["./scripts/run-demo.sh"],
      "cwd": "."
    }
  }
}
`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "mcp_portability" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected mcp_portability failure for repo-relative MCP launch")
	}
}

func TestCheck_MCPPortabilityFlagsGeneratedConfigCWD(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", `{
  "mcpServers": {
    "demo": {
      "command": "bash",
      "args": ["-c", "exec bash \"$HOME/demo.sh\""]
    }
  }
}
`)
	writeFile(t, dir, ".codex/config.toml", `
[mcp_servers.demo]
cwd = "."
`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "mcp_portability" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected mcp_portability failure for generated config cwd")
	}
}

func TestCheck_DashCaseAgent(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".codex/agents/my-agent.toml", `name = "my-agent"`)

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "agent_naming" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected agent_naming failure for dash-case filename")
	}
}

func TestCheck_InvalidSurfaceJSON(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/skills/surface.yaml", "not json at all")

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "skill_surface" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected skill_surface failure for invalid JSON")
	}
}

func TestCheck_MissingSkillFile(t *testing.T) {
	dir := setupCompliantRepo(t)
	os.RemoveAll(filepath.Join(dir, ".agents/skills/test_skill"))

	report := Check(dir)
	found := false
	for _, f := range report.Findings {
		if f.Check == "skill_file" && !f.Passed {
			found = true
		}
	}
	if !found {
		t.Error("expected skill_file failure for missing SKILL.md")
	}
}

func TestCheck_SkillSurfaceVersion2(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/skills/surface.yaml", `{
  "version": 2,
  "plugin_root": "demo",
  "export_all_to_plugin": true,
  "skills": [{"name": "test_skill", "type": "workflow"}]
}`)

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "skill_surface" && !f.Passed {
			t.Fatalf("version 2 surface should pass, got finding: %+v", f)
		}
	}
}

func TestCheck_NoSurface(t *testing.T) {
	dir := setupCompliantRepo(t)
	os.Remove(filepath.Join(dir, ".agents/skills/surface.yaml"))

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "skill_surface" && !f.Passed {
			t.Error("missing surface.yaml should not cause failure")
		}
	}
}

func TestCheck_SkillSurfaceAcceptsVersion2(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/skills/surface.yaml", `{"version":2,"skills":[{"name":"test_skill"}]}`)

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "skill_surface" {
			if !f.Passed {
				t.Fatalf("skill_surface failed: %s", f.Message)
			}
			return
		}
	}
	t.Fatal("skill_surface finding missing")
}

func TestCheck_SkillSyncAllowsGeneratedClaudeMirror(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".agents/skills/surface.yaml", `{"version":1,"skills":[{"name":"test_skill","claude_include_canonical":true}]}`)
	writeFile(t, dir, ".agents/skills/test_skill/SKILL.md", `---
name: test_skill
description: "Core build, test, release, and maintenance workflow for the test repo."
allowed-tools:
  - Bash
---

# Test Skill

Use this skill for the default repo workflow.
`)
	writeFile(t, dir, ".claude/skills/test_skill/SKILL.md", `---
name: test_skill
description: 'Core build, test, release, and maintenance workflow for the test repo.'
allowed-tools:
  - Bash
---

<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->

Compatibility mirror of the canonical `+"`test_skill`"+` skill.


# Test Skill

Use this skill for the default repo workflow.
`)
	writeFile(t, dir, ".claude/skills/test-skill/SKILL.md", `---
name: test-skill
description: 'Hyphenated compatibility alias for the test_skill workflow.'
allowed-tools:
  - Bash
---

<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->

Compatibility alias for the canonical `+"`test_skill`"+` skill.


# Test Skill

Use this skill for the default repo workflow.
`)

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "skill_sync" && !f.Passed {
			t.Fatalf("expected generated Claude mirror to pass, got: %s", f.Message)
		}
	}
}

func TestCheck_MCPSyncHonorsProfilePolicy(t *testing.T) {
	dir := setupCompliantRepo(t)
	writeFile(t, dir, ".mcp.json", `{
  "mcpServers": {
    "demo": {
      "command": "bash",
      "args": ["-lc", "exec ./scripts/run-demo.sh"]
    }
  }
}
`)
	writeFile(t, dir, ".codex/mcp-profile-policy.json", `{
  "version": 1,
  "profiles": [
    {
      "name": "demo_review",
      "from": "demo",
      "comment": "Read-only demo profile."
    }
  ]
}
`)
	writeFile(t, dir, ".codex/config.toml", `
approval_policy = "on-request"
`)
	if report := mcpsync.Sync(dir, false); len(report.Errors) > 0 {
		t.Fatalf("unexpected mcpsync errors: %v", report.Errors)
	}

	report := Check(dir)
	for _, f := range report.Findings {
		if f.Check == "mcp_sync" && !f.Passed {
			t.Fatalf("expected policy-derived MCP server to pass, got: %s", f.Message)
		}
	}
}

// --- model_pin_freshness ---

// withNow overrides the package clock for the duration of a test.
func withNow(t *testing.T, ts string) {
	t.Helper()
	parsed, err := time.Parse("2006-01-02", ts)
	if err != nil {
		t.Fatal(err)
	}
	orig := nowFunc
	nowFunc = func() time.Time { return parsed }
	t.Cleanup(func() { nowFunc = orig })
}

// setupLifecycleRepo returns a repo dir whose parent contains a
// workspace/model-lifecycle.json registry with the given raw JSON body.
func setupLifecycleRepo(t *testing.T, registryJSON string) string {
	t.Helper()
	root := t.TempDir()
	repoDir := filepath.Join(root, "repo")
	if err := os.MkdirAll(repoDir, 0755); err != nil {
		t.Fatal(err)
	}
	if registryJSON != "" {
		writeFile(t, root, filepath.Join("workspace", "model-lifecycle.json"), registryJSON)
	}
	return repoDir
}

func findingsFor(report Report, check string) []Finding {
	var out []Finding
	for _, f := range report.Findings {
		if f.Check == check {
			out = append(out, f)
		}
	}
	return out
}

func TestModelPinFreshness_RetiredPinFails(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupLifecycleRepo(t, `{
  "version": 1,
  "models": [
    {"id": "foo-model", "aliases": [], "provider": "test", "status": "deprecated", "retires": "2026-07-15", "replacement": "foo-replacement"}
  ]
}`)
	writeFile(t, dir, ".codex/config.toml", `model = "foo-model"`)

	report := Check(dir)
	findings := findingsFor(report, "model_pin_freshness")
	if len(findings) != 1 {
		t.Fatalf("expected 1 model_pin_freshness finding, got %d: %#v", len(findings), findings)
	}
	f := findings[0]
	if f.Passed {
		t.Fatalf("expected FAIL for retired pin, got PASS: %s", f.Message)
	}
	want := "retired model pin foo-model in .codex/config.toml — migrate to foo-replacement"
	if f.Message != want {
		t.Errorf("message = %q, want %q", f.Message, want)
	}
}

func TestModelPinFreshness_TenDaysOutFails(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupLifecycleRepo(t, `{
  "version": 1,
  "models": [
    {"id": "foo-model", "aliases": [], "provider": "test", "status": "deprecated", "retires": "2026-08-11", "replacement": "foo-replacement"}
  ]
}`)
	writeFile(t, dir, ".codex/config.toml", `model = "foo-model"`)

	report := Check(dir)
	findings := findingsFor(report, "model_pin_freshness")
	if len(findings) != 1 {
		t.Fatalf("expected 1 model_pin_freshness finding, got %d: %#v", len(findings), findings)
	}
	if findings[0].Passed {
		t.Fatalf("expected FAIL for pin retiring in 10 days, got PASS: %s", findings[0].Message)
	}
}

func TestModelPinFreshness_TwentyDaysOutPassesWithNote(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupLifecycleRepo(t, `{
  "version": 1,
  "models": [
    {"id": "foo-model", "aliases": [], "provider": "test", "status": "deprecated", "retires": "2026-08-21", "replacement": "foo-replacement"}
  ]
}`)
	writeFile(t, dir, ".codex/config.toml", `model = "foo-model"`)

	report := Check(dir)
	findings := findingsFor(report, "model_pin_freshness")
	if len(findings) != 1 {
		t.Fatalf("expected 1 model_pin_freshness finding, got %d: %#v", len(findings), findings)
	}
	if !findings[0].Passed {
		t.Fatalf("expected PASS-with-note for pin retiring in 20 days, got FAIL: %s", findings[0].Message)
	}
	want := "deprecated model pin foo-model — plan migration to foo-replacement"
	if findings[0].Message != want {
		t.Errorf("message = %q, want %q", findings[0].Message, want)
	}
}

func TestModelPinFreshness_NoDateDeprecatedPassesWithNote(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupLifecycleRepo(t, `{
  "version": 1,
  "models": [
    {"id": "foo-model", "aliases": [], "provider": "test", "status": "deprecated", "retires": null, "replacement": "foo-replacement"}
  ]
}`)
	writeFile(t, dir, ".codex/config.toml", `model = "foo-model"`)

	report := Check(dir)
	findings := findingsFor(report, "model_pin_freshness")
	if len(findings) != 1 {
		t.Fatalf("expected 1 model_pin_freshness finding, got %d: %#v", len(findings), findings)
	}
	if !findings[0].Passed {
		t.Fatalf("expected PASS-with-note for undated deprecated pin, got FAIL: %s", findings[0].Message)
	}
}

func TestModelPinFreshness_AbsentRegistrySkips(t *testing.T) {
	dir := setupLifecycleRepo(t, "")
	writeFile(t, dir, ".codex/config.toml", `model = "foo-model"`)

	report := Check(dir)
	findings := findingsFor(report, "model_pin_freshness")
	if len(findings) != 1 || !findings[0].Passed {
		t.Fatalf("expected single informational pass finding for absent registry, got %#v", findings)
	}
	want := "model lifecycle registry absent — skipping"
	if findings[0].Message != want {
		t.Errorf("message = %q, want %q", findings[0].Message, want)
	}
}

func TestModelPinFreshness_OverlapGuardDoesNotDoubleReport(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupLifecycleRepo(t, `{
  "version": 1,
  "models": [
    {"id": "gpt-5.4", "aliases": [], "provider": "openai", "status": "deprecated", "retires": null, "replacement": "gpt-5.6-terra"},
    {"id": "gpt-5.4-mini", "aliases": [], "provider": "openai", "status": "deprecated", "retires": null, "replacement": "gpt-5.6-luna"}
  ]
}`)
	writeFile(t, dir, ".codex/config.toml", `model = "gpt-5.4-mini"`)

	report := Check(dir)
	findings := findingsFor(report, "model_pin_freshness")
	if len(findings) != 1 {
		t.Fatalf("expected exactly 1 model_pin_freshness finding (no double report), got %d: %#v", len(findings), findings)
	}
	want := "deprecated model pin gpt-5.4-mini — plan migration to gpt-5.6-luna"
	if findings[0].Message != want {
		t.Errorf("message = %q, want %q (gpt-5.4 must not have matched)", findings[0].Message, want)
	}
}

// --- mcp_spec_target ---

func setupSpecTargetRepo(t *testing.T, protocolVersion, registryJSON string) string {
	t.Helper()
	root := t.TempDir()
	repoDir := filepath.Join(root, "repo")
	if err := os.MkdirAll(repoDir, 0755); err != nil {
		t.Fatal(err)
	}
	if protocolVersion != "" {
		writeFile(t, repoDir, filepath.Join(".well-known", "mcp.json"), `{"protocolVersion": "`+protocolVersion+`"}`)
	}
	if registryJSON != "" {
		writeFile(t, root, filepath.Join("workspace", "mcp-spec-target.json"), registryJSON)
	}
	return repoDir
}

const testSpecRegistry = `{"version":1,"current":"2026-07-28","fleet_target":"2025-11-25","compat_deadline":"2027-07-28"}`

func TestMCPSpecTarget_OlderThanFleetTargetFails(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupSpecTargetRepo(t, "2024-11-05", testSpecRegistry)

	report := Check(dir)
	findings := findingsFor(report, "mcp_spec_target")
	if len(findings) != 1 {
		t.Fatalf("expected 1 mcp_spec_target finding, got %d: %#v", len(findings), findings)
	}
	if findings[0].Passed {
		t.Fatalf("expected FAIL for spec older than fleet target, got PASS: %s", findings[0].Message)
	}
}

func TestMCPSpecTarget_EqualsFleetTargetPassesWithNote(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupSpecTargetRepo(t, "2025-11-25", testSpecRegistry)

	report := Check(dir)
	findings := findingsFor(report, "mcp_spec_target")
	if len(findings) != 1 {
		t.Fatalf("expected 1 mcp_spec_target finding, got %d: %#v", len(findings), findings)
	}
	if !findings[0].Passed {
		t.Fatalf("expected PASS-with-note at fleet target, got FAIL: %s", findings[0].Message)
	}
	want := "spec 2025-11-25 behind current 2026-07-28; compat window until 2027-07-28"
	if findings[0].Message != want {
		t.Errorf("message = %q, want %q", findings[0].Message, want)
	}
}

func TestMCPSpecTarget_EqualsCurrentCleanPass(t *testing.T) {
	withNow(t, "2026-08-01")
	dir := setupSpecTargetRepo(t, "2026-07-28", testSpecRegistry)

	report := Check(dir)
	findings := findingsFor(report, "mcp_spec_target")
	if len(findings) != 1 {
		t.Fatalf("expected 1 mcp_spec_target finding, got %d: %#v", len(findings), findings)
	}
	if !findings[0].Passed {
		t.Fatalf("expected clean PASS at current spec, got FAIL: %s", findings[0].Message)
	}
}

func TestMCPSpecTarget_AbsentFileSkips(t *testing.T) {
	dir := setupSpecTargetRepo(t, "", testSpecRegistry)

	report := Check(dir)
	findings := findingsFor(report, "mcp_spec_target")
	if len(findings) != 0 {
		t.Fatalf("expected no mcp_spec_target findings when .well-known/mcp.json is absent, got %#v", findings)
	}
}

func TestMCPSpecTarget_PastDeadlineFails(t *testing.T) {
	withNow(t, "2027-08-01") // past compat_deadline 2027-07-28
	dir := setupSpecTargetRepo(t, "2025-11-25", testSpecRegistry)

	report := Check(dir)
	findings := findingsFor(report, "mcp_spec_target")
	if len(findings) != 1 {
		t.Fatalf("expected 1 mcp_spec_target finding, got %d: %#v", len(findings), findings)
	}
	if findings[0].Passed {
		t.Fatalf("expected FAIL once compat deadline has passed, got PASS: %s", findings[0].Message)
	}
}

// realRalphglassesWellKnownPath is codexkit's own submodule-relative path to
// the ralphglasses superproject's .well-known/mcp.json. codexkit is also
// published standalone (its own mirror repo), where this superproject file
// does not exist — TestMCPSpecTarget_RalphglassesOwnFileMeetsCurrent skips in
// that case rather than failing a repo that has no opinion about
// ralphglasses' spec version.
const realRalphglassesWellKnownPath = "../../../.well-known/mcp.json"

// TestMCPSpecTarget_RalphglassesOwnFileMeetsCurrent wires the mcp_spec_target
// check to ralphglasses' own .well-known/mcp.json so a future regression
// (e.g. someone reverting the protocolVersion bump) is caught by this
// package's own test suite, not just by fleet-wide baseline_check_all.
func TestMCPSpecTarget_RalphglassesOwnFileMeetsCurrent(t *testing.T) {
	data, err := os.ReadFile(realRalphglassesWellKnownPath)
	if err != nil {
		t.Skipf("codexkit checked out standalone (no ralphglasses superproject found): %v", err)
	}
	var doc struct {
		ProtocolVersion string `json:"protocolVersion"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("ralphglasses .well-known/mcp.json is not valid JSON: %v", err)
	}

	withNow(t, "2026-08-08")
	dir := setupSpecTargetRepo(t, doc.ProtocolVersion, testSpecRegistry)

	report := Check(dir)
	findings := findingsFor(report, "mcp_spec_target")
	if len(findings) != 1 {
		t.Fatalf("expected 1 mcp_spec_target finding, got %d: %#v", len(findings), findings)
	}
	if !findings[0].Passed {
		t.Fatalf("ralphglasses' own .well-known/mcp.json (protocolVersion %q) fails the fleet mcp-spec-target check: %s — bump .well-known/mcp.json's protocolVersion", doc.ProtocolVersion, findings[0].Message)
	}
	if !strings.Contains(findings[0].Message, "matches current") {
		t.Errorf("ralphglasses' own .well-known/mcp.json (protocolVersion %q) is behind the fleet-current MCP spec, not just within a compat window: %s", doc.ProtocolVersion, findings[0].Message)
	}
}

// --- config_drift ---

func setupConfigExpectationRepo(t *testing.T, registryJSON string) string {
	t.Helper()
	root := t.TempDir()
	repoDir := filepath.Join(root, "repo")
	if err := os.MkdirAll(repoDir, 0755); err != nil {
		t.Fatal(err)
	}
	if registryJSON != "" {
		writeFile(t, root, filepath.Join("workspace", "config-expectations.json"), registryJSON)
	}
	return repoDir
}

const testConfigExpectations = `{
  "version": 1,
  "expectations": [
    {
      "id": "codex-safe-default",
      "provider": "codex",
      "repos": ["repo"],
      "file": ".codex/config.toml",
      "format": "toml",
      "expected": {
        "approval_policy": "on-request",
        "sandbox_mode": "workspace-write"
      },
      "forbidden": ["profiles"]
    },
    {
      "id": "claude-launch-contract",
      "provider": "claude",
      "repos": ["repo"],
      "file": "scripts/hg-claude-launch.sh",
      "format": "text",
      "expected_contains": ["--provider claude"],
      "forbidden_contains": ["--dangerously-skip-permissions"]
    }
  ]
}`

func TestConfigDrift_RegisteredConfigAndLauncherPass(t *testing.T) {
	dir := setupConfigExpectationRepo(t, testConfigExpectations)
	writeFile(t, dir, ".codex/config.toml", "approval_policy = \"on-request\"\nsandbox_mode = \"workspace-write\"\n")
	writeFile(t, dir, "scripts/hg-claude-launch.sh", "exec runner --provider claude -- \"$@\"\n")

	findings := findingsFor(Check(dir), "config_drift")
	if len(findings) != 2 {
		t.Fatalf("expected two config_drift pass findings, got %d: %#v", len(findings), findings)
	}
	for _, finding := range findings {
		if !finding.Passed {
			t.Fatalf("expected registered config to pass, got: %s", finding.Message)
		}
	}
}

func TestConfigDrift_NegativeControlDetectsMutatedExpectedValue(t *testing.T) {
	dir := setupConfigExpectationRepo(t, testConfigExpectations)
	writeFile(t, dir, ".codex/config.toml", "approval_policy = \"never\"\nsandbox_mode = \"workspace-write\"\n")
	writeFile(t, dir, "scripts/hg-claude-launch.sh", "exec runner --provider claude -- \"$@\"\n")

	findings := findingsFor(Check(dir), "config_drift")
	failed := 0
	for _, finding := range findings {
		if !finding.Passed {
			failed++
			if !strings.Contains(finding.Message, "approval_policy") {
				t.Fatalf("negative control failed for the wrong reason: %s", finding.Message)
			}
		}
	}
	if failed != 1 {
		t.Fatalf("expected exactly one negative-control failure, got %d: %#v", failed, findings)
	}
}

func TestConfigDrift_ForbiddenStructuredKeyFails(t *testing.T) {
	dir := setupConfigExpectationRepo(t, testConfigExpectations)
	writeFile(t, dir, ".codex/config.toml", "approval_policy = \"on-request\"\nsandbox_mode = \"workspace-write\"\n[profiles.review]\nmodel = \"test\"\n")
	writeFile(t, dir, "scripts/hg-claude-launch.sh", "exec runner --provider claude -- \"$@\"\n")

	findings := findingsFor(Check(dir), "config_drift")
	if len(findings) < 1 || findings[0].Passed || !strings.Contains(findings[0].Message, "forbidden key profiles") {
		t.Fatalf("expected forbidden profiles table to fail, got %#v", findings)
	}
}

func TestConfigDrift_ForbiddenLauncherFlagFails(t *testing.T) {
	dir := setupConfigExpectationRepo(t, testConfigExpectations)
	writeFile(t, dir, ".codex/config.toml", "approval_policy = \"on-request\"\nsandbox_mode = \"workspace-write\"\n")
	writeFile(t, dir, "scripts/hg-claude-launch.sh", "exec runner --provider claude --dangerously-skip-permissions -- \"$@\"\n")

	findings := findingsFor(Check(dir), "config_drift")
	if len(findings) != 2 || findings[1].Passed || !strings.Contains(findings[1].Message, "forbidden launcher contract") {
		t.Fatalf("expected forbidden launcher flag to fail, got %#v", findings)
	}
}

func TestConfigDrift_MalformedRegistryFailsClosed(t *testing.T) {
	dir := setupConfigExpectationRepo(t, `{not-json`)

	findings := findingsFor(Check(dir), "config_drift")
	if len(findings) != 1 || findings[0].Passed || !strings.Contains(findings[0].Message, "invalid config expectations registry") {
		t.Fatalf("expected malformed registry to fail closed, got %#v", findings)
	}
}

func TestConfigDrift_AbsentRegistrySkips(t *testing.T) {
	dir := setupConfigExpectationRepo(t, "")

	findings := findingsFor(Check(dir), "config_drift")
	if len(findings) != 1 || !findings[0].Passed || findings[0].Message != "config expectations registry absent — skipping" {
		t.Fatalf("expected absent registry to skip, got %#v", findings)
	}
}
