package fleetaudit

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// writeAuditFile writes content to base/name, creating parent dirs as needed.
func writeAuditFile(t *testing.T, base, name, content string) {
	t.Helper()
	path := filepath.Join(base, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

// setupBaselineCompliantRepo builds a repo that passes baselineguard.Check
// so a fleetaudit test can isolate the behavior under test (e.g. mcp_sync)
// without unrelated baseline findings failing the repo first.
func setupBaselineCompliantRepo(t *testing.T, dir string) {
	t.Helper()
	writeAuditFile(t, dir, "AGENTS.md", "# Test\n\n> Canonical instructions: AGENTS.md\n")
	writeAuditFile(t, dir, "CLAUDE.md", "# Test\n\nThis repo uses [AGENTS.md](AGENTS.md) as the canonical instruction file.\n")
	writeAuditFile(t, dir, ".claude/settings.json", "{}\n")
	writeAuditFile(t, dir, ".agents/hooks.json", "{}\n")
	writeAuditFile(t, dir, ".agents/agents/reviewer/agent.md", "---\nname: reviewer\ndescription: Review changes.\n---\n")
	writeAuditFile(t, dir, ".codex/config.toml", "approval_policy = \"on-request\"\n")
	writeAuditFile(t, dir, ".codex/agents/reviewer.toml", `name = "reviewer"`)
	writeAuditFile(t, dir, ".codex/agents/repo_explorer.toml", `name = "repo_explorer"`)

	surface, _ := json.Marshal(map[string]any{
		"version": 1,
		"skills":  []map[string]any{{"name": "test_skill"}},
	})
	writeAuditFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeAuditFile(t, dir, ".agents/skills/test_skill/SKILL.md", "---\nname: test_skill\ndescription: \"Core build, test, release, and maintenance workflow for the test repo.\"\nallowed-tools:\n  - Bash\n---\n# Test\n")
	writeAuditFile(t, dir, ".claude/skills/test_skill/SKILL.md", "---\nname: test_skill\ndescription: 'Core build, test, release, and maintenance workflow for the test repo.'\nallowed-tools:\n  - Bash\n---\n\n<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->\n\nCompatibility mirror of the canonical `test_skill` skill.\n\n\n# Test\n")
	writeAuditFile(t, dir, ".claude/skills/test-skill/SKILL.md", "---\nname: test-skill\ndescription: 'Hyphenated compatibility alias for the test_skill workflow.'\nallowed-tools:\n  - Bash\n---\n\n<!-- GENERATED BY hg-skill-surface-sync.sh FROM .agents/skills/test_skill/SKILL.md; DO NOT EDIT -->\n\nCompatibility alias for the canonical `test_skill` skill.\n\n\n# Test\n")
}

func TestAudit_EmptyDir(t *testing.T) {
	dir := t.TempDir()
	report := Audit(dir)

	if report.ScanPath != dir {
		t.Errorf("ScanPath = %q, want %q", report.ScanPath, dir)
	}
	if report.TotalRepos != 0 {
		t.Errorf("TotalRepos = %d, want 0", report.TotalRepos)
	}
	if len(report.Repos) != 0 {
		t.Errorf("Repos = %d entries, want 0", len(report.Repos))
	}
}

func TestAudit_NonexistentDir(t *testing.T) {
	report := Audit("/nonexistent-path-that-does-not-exist")

	if report.TotalRepos != 0 {
		t.Errorf("TotalRepos = %d, want 0 for nonexistent dir", report.TotalRepos)
	}
}

func TestAudit_SkipsNonGitDirs(t *testing.T) {
	dir := t.TempDir()
	// Create a subdirectory without .git
	if err := os.MkdirAll(filepath.Join(dir, "not-a-repo"), 0755); err != nil {
		t.Fatal(err)
	}

	report := Audit(dir)
	if report.TotalRepos != 0 {
		t.Errorf("TotalRepos = %d, want 0 (should skip non-git dirs)", report.TotalRepos)
	}
}

func TestAudit_SkipsFiles(t *testing.T) {
	dir := t.TempDir()
	// Create a regular file in scan dir
	if err := os.WriteFile(filepath.Join(dir, "somefile.txt"), []byte("hi"), 0644); err != nil {
		t.Fatal(err)
	}

	report := Audit(dir)
	if report.TotalRepos != 0 {
		t.Errorf("TotalRepos = %d, want 0 (should skip files)", report.TotalRepos)
	}
}

func TestAudit_DetectsGitRepo(t *testing.T) {
	dir := t.TempDir()
	repoDir := filepath.Join(dir, "test-repo")
	if err := os.MkdirAll(filepath.Join(repoDir, ".git"), 0755); err != nil {
		t.Fatal(err)
	}

	report := Audit(dir)
	if report.TotalRepos != 1 {
		t.Fatalf("TotalRepos = %d, want 1", report.TotalRepos)
	}
	if report.Repos[0].RepoName != "test-repo" {
		t.Errorf("RepoName = %q, want %q", report.Repos[0].RepoName, "test-repo")
	}
	if report.Repos[0].RepoPath != repoDir {
		t.Errorf("RepoPath = %q, want %q", report.Repos[0].RepoPath, repoDir)
	}
}

func TestAudit_PassedCountsMatchRepos(t *testing.T) {
	dir := t.TempDir()
	// Create two mock repos
	for _, name := range []string{"repo-a", "repo-b"} {
		if err := os.MkdirAll(filepath.Join(dir, name, ".git"), 0755); err != nil {
			t.Fatal(err)
		}
	}

	report := Audit(dir)
	if report.TotalRepos != 2 {
		t.Fatalf("TotalRepos = %d, want 2", report.TotalRepos)
	}
	if report.Passed+report.Failed != report.TotalRepos {
		t.Errorf("Passed(%d) + Failed(%d) != TotalRepos(%d)",
			report.Passed, report.Failed, report.TotalRepos)
	}
}

// TestAudit_AbsentMCPConfigDoesNotFailRepo is a regression test: a repo with
// no .mcp.json is a legitimate state (baselineguard.addMCPSyncCheck skips
// its own mcp_sync finding entirely when the file is absent), so fleetaudit
// must not fold mcpsync.Diff's "reading .mcp.json: ... no such file" error
// into audit.Passed = false.
func TestAudit_AbsentMCPConfigDoesNotFailRepo(t *testing.T) {
	dir := t.TempDir()
	repoDir := filepath.Join(dir, "no-mcp-repo")
	if err := os.MkdirAll(filepath.Join(repoDir, ".git"), 0755); err != nil {
		t.Fatal(err)
	}
	setupBaselineCompliantRepo(t, repoDir)
	// Deliberately no .mcp.json.

	report := Audit(dir)
	if report.TotalRepos != 1 {
		t.Fatalf("TotalRepos = %d, want 1", report.TotalRepos)
	}
	audit := report.Repos[0]
	if len(audit.MCPSync.Errors) == 0 {
		t.Fatal("expected mcpsync.Diff to report an error for absent .mcp.json (test setup assumption changed)")
	}
	if !audit.Baseline.Passed {
		for _, f := range audit.Baseline.Findings {
			if !f.Passed {
				t.Logf("baseline finding failed: %s — %s", f.Check, f.Message)
			}
		}
		t.Fatal("expected baseline to pass for the compliant repo fixture")
	}
	if !audit.Passed {
		t.Error("audit.Passed = false, want true — absent .mcp.json must not fail the repo")
	}
	if report.Failed != 0 {
		t.Errorf("report.Failed = %d, want 0", report.Failed)
	}
	if report.Passed != 1 {
		t.Errorf("report.Passed = %d, want 1", report.Passed)
	}
}

func TestModule_NameAndInit(t *testing.T) {
	m := Module()
	if m.Name() != "fleetaudit" {
		t.Errorf("Name() = %q, want %q", m.Name(), "fleetaudit")
	}
	if err := m.Init(); err != nil {
		t.Errorf("Init() = %v, want nil", err)
	}
}

func TestModule_ToolCount(t *testing.T) {
	m := Module()
	tools := m.Tools()
	if len(tools) != 2 {
		t.Errorf("len(Tools()) = %d, want 2", len(tools))
	}

	names := map[string]bool{}
	for _, tool := range tools {
		names[tool.Name] = true
	}
	for _, want := range []string{"fleet_audit", "fleet_report"} {
		if !names[want] {
			t.Errorf("missing tool %q", want)
		}
	}
}

func TestModule_FleetAuditHandler(t *testing.T) {
	dir := t.TempDir()
	m := Module()
	tools := m.Tools()

	var auditTool func(map[string]any) (any, error)
	for _, tool := range tools {
		if tool.Name == "fleet_audit" {
			auditTool = tool.Handler
			break
		}
	}
	if auditTool == nil {
		t.Fatal("fleet_audit tool not found")
	}

	result, err := auditTool(map[string]any{"scan_path": dir})
	if err != nil {
		t.Fatalf("fleet_audit handler error: %v", err)
	}
	report, ok := result.(FleetReport)
	if !ok {
		t.Fatalf("fleet_audit returned %T, want FleetReport", result)
	}
	if report.ScanPath != dir {
		t.Errorf("ScanPath = %q, want %q", report.ScanPath, dir)
	}
}

func TestModule_FleetReportHandler(t *testing.T) {
	dir := t.TempDir()
	m := Module()
	tools := m.Tools()

	var reportTool func(map[string]any) (any, error)
	for _, tool := range tools {
		if tool.Name == "fleet_report" {
			reportTool = tool.Handler
			break
		}
	}
	if reportTool == nil {
		t.Fatal("fleet_report tool not found")
	}

	result, err := reportTool(map[string]any{"scan_path": dir})
	if err != nil {
		t.Fatalf("fleet_report handler error: %v", err)
	}
	s, ok := result.(string)
	if !ok {
		t.Fatalf("fleet_report returned %T, want string", result)
	}
	if s == "" {
		t.Error("fleet_report returned empty string")
	}
}
