package skillsync

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, base, name, content string) {
	t.Helper()
	path := filepath.Join(base, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func setupSyncRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()

	surface, _ := json.Marshal(map[string]any{
		"version":     1,
		"plugin_root": "demo",
		"skills": []map[string]any{{
			"name":          "myskill",
			"export_plugin": true,
		}},
	})
	writeFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeFile(t, dir, ".agents/skills/myskill/SKILL.md", "---\nname: myskill\ndescription: test skill\n---\n# My Skill\n")

	return dir
}

func TestSync_CreatesClaudeMirror(t *testing.T) {
	dir := setupSyncRepo(t)

	report := Sync(dir, false)
	if len(report.Errors) > 0 {
		t.Fatalf("unexpected errors: %v", report.Errors)
	}

	// Check .claude/skills mirror was created
	path := filepath.Join(dir, ".claude/skills/myskill/SKILL.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("mirror not created: %v", err)
	}

	if !strings.Contains(string(data), "# My Skill") {
		t.Error("mirror should embed the canonical skill body")
	}
	if !strings.Contains(string(data), "GENERATED BY hg-skill-surface-sync.sh") {
		t.Error("mirror should include the generated banner")
	}

	// Check plugins mirror was created
	pluginPath := filepath.Join(dir, "plugins/demo/skills/myskill/SKILL.md")
	if _, err := os.Stat(pluginPath); err != nil {
		t.Fatalf("plugins mirror not created: %v", err)
	}
}

func TestSync_DryRunNoWrite(t *testing.T) {
	dir := setupSyncRepo(t)

	report := Sync(dir, true)
	if len(report.Errors) > 0 {
		t.Fatalf("unexpected errors: %v", report.Errors)
	}

	path := filepath.Join(dir, ".claude/skills/myskill/SKILL.md")
	if _, err := os.Stat(path); err == nil {
		t.Error("dry-run should not create files")
	}

	// Should have create actions
	hasCreate := false
	for _, a := range report.Actions {
		if a.Action == "create" {
			hasCreate = true
		}
	}
	if !hasCreate {
		t.Error("expected create actions in dry-run report")
	}
}

func TestSync_DetectsUnchanged(t *testing.T) {
	dir := setupSyncRepo(t)

	// First sync
	Sync(dir, false)

	// Second sync — should detect unchanged
	report := Sync(dir, false)
	for _, a := range report.Actions {
		if a.Action != "unchanged" {
			t.Errorf("expected unchanged, got %s for %s", a.Action, a.DstPath)
		}
	}
}

func TestSync_RemovesStaleManagedMirrors(t *testing.T) {
	dir := setupSyncRepo(t)
	staleClaudeDir := filepath.Join(dir, ".claude/skills/stale-skill")
	stalePluginDir := filepath.Join(dir, "plugins/demo/skills/stale-skill")
	writeFile(t, dir, ".claude/skills/stale-skill/SKILL.md", "# stale\n")
	writeFile(t, dir, "plugins/demo/skills/stale-skill/SKILL.md", "# stale\n")

	report := Sync(dir, false)
	if len(report.Errors) > 0 {
		t.Fatalf("unexpected errors: %v", report.Errors)
	}
	if _, err := os.Stat(staleClaudeDir); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("stale Claude skill dir should be removed, stat err = %v", err)
	}
	if _, err := os.Stat(stalePluginDir); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("stale plugin skill dir should be removed, stat err = %v", err)
	}

	removed := 0
	for _, action := range report.Actions {
		if action.Action == "remove" {
			removed++
		}
	}
	if removed != 2 {
		t.Fatalf("expected 2 remove actions, got %d", removed)
	}
}

func TestSync_RejectsNonPortableFrontmatter(t *testing.T) {
	dir := t.TempDir()
	surface, _ := json.Marshal(map[string]any{
		"version": 1,
		"skills": []map[string]any{{
			"name": "myskill",
		}},
	})
	writeFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeFile(t, dir, ".agents/skills/myskill/SKILL.md", "---\nname: myskill\ndescription: bad skill\nreload: true\n---\n# My Skill\n")

	report := Sync(dir, false)
	if len(report.Errors) == 0 {
		t.Fatal("expected non-portable frontmatter error")
	}
	if !strings.Contains(report.Errors[0], "non-portable frontmatter") {
		t.Fatalf("expected non-portable frontmatter error, got %v", report.Errors)
	}
}

func TestDiff_IsDryRun(t *testing.T) {
	dir := setupSyncRepo(t)
	report := Diff(dir)
	if !report.DryRun {
		t.Error("Diff should set DryRun=true")
	}
}

func TestList_ReturnsSkillNames(t *testing.T) {
	dir := setupSyncRepo(t)
	names, err := List(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(names) != 1 || names[0] != "myskill" {
		t.Errorf("expected [myskill], got %v", names)
	}
}

func TestFilterPortableFrontmatter(t *testing.T) {
	input := "---\nname: test\ncustom_key: bad\ndescription: good\n---\n# Content\n"
	result := FilterPortableFrontmatter(input)
	if strings.Contains(result, "custom_key") {
		t.Error("non-portable key should be filtered")
	}
	if !strings.Contains(result, "name: test") {
		t.Error("portable key 'name' should be preserved")
	}
	if !strings.Contains(result, "description: good") {
		t.Error("portable key 'description' should be preserved")
	}
}

func TestFilterPortableFrontmatter_PreservesReload(t *testing.T) {
	input := "---\nname: test\nreload: true\n---\n# Content\n"
	result := FilterPortableFrontmatter(input)
	if strings.Contains(result, "reload: true") {
		t.Error("reload key should be filtered from portable frontmatter")
	}
}

func TestParseSurface_YAML(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".agents/skills/surface.yaml", "version: 1\nskills:\n  - name: alpha\n  - name: beta\n")

	surface, err := ParseSurface(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(surface.Skills) != 2 {
		t.Errorf("expected 2 skills, got %d", len(surface.Skills))
	}
}

func TestSync_AddsHyphenAliasForUnderscoreSkills(t *testing.T) {
	dir := t.TempDir()
	surface, _ := json.Marshal(map[string]any{
		"version": 1,
		"skills": []map[string]any{{
			"name": "my_skill",
		}},
	})
	writeFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeFile(t, dir, ".agents/skills/my_skill/SKILL.md", "---\nname: my_skill\ndescription: underscore skill\n---\n# My Skill\n")

	report := Sync(dir, false)
	if len(report.Errors) > 0 {
		t.Fatalf("unexpected errors: %v", report.Errors)
	}

	canonicalPath := filepath.Join(dir, ".claude/skills/my_skill/SKILL.md")
	normalizedPath := filepath.Join(dir, ".claude/skills/my-skill/SKILL.md")

	if _, err := os.Stat(canonicalPath); err != nil {
		t.Fatalf("canonical Claude mirror missing: %v", err)
	}
	data, err := os.ReadFile(normalizedPath)
	if err != nil {
		t.Fatalf("normalized Claude alias missing: %v", err)
	}
	text := string(data)
	if !strings.Contains(text, "name: my-skill") {
		t.Fatalf("normalized alias should rewrite name frontmatter: %s", text)
	}
	if !strings.Contains(text, "Hyphenated compatibility alias for the my_skill workflow.") {
		t.Fatalf("normalized alias should describe the compatibility bridge: %s", text)
	}
}

func TestSync_DoesNotDuplicateExplicitNormalizedAlias(t *testing.T) {
	dir := t.TempDir()
	surface, _ := json.Marshal(map[string]any{
		"version": 1,
		"skills": []map[string]any{{
			"name": "my_skill",
			"claude_aliases": []map[string]any{{
				"name":        "my-skill",
				"description": "explicit alias",
			}},
		}},
	})
	writeFile(t, dir, ".agents/skills/surface.yaml", string(surface))
	writeFile(t, dir, ".agents/skills/my_skill/SKILL.md", "---\nname: my_skill\ndescription: underscore skill\n---\n# My Skill\n")

	report := Sync(dir, false)
	if len(report.Errors) > 0 {
		t.Fatalf("unexpected errors: %v", report.Errors)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".claude/skills/my-skill/SKILL.md"))
	if err != nil {
		t.Fatalf("expected explicit normalized alias file: %v", err)
	}
	if !strings.Contains(string(data), "description: 'explicit alias'") {
		t.Fatalf("expected explicit alias description to win, got: %s", string(data))
	}
}
